/* Generated by wayland-scanner 1.12.0 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface _wl_fullscreen_shell_mode_feedback_interface;
extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *types[] = {
	NULL,
	&wl_surface_interface,
	NULL,
	&wl_output_interface,
	&wl_surface_interface,
	&wl_output_interface,
	NULL,
	&_wl_fullscreen_shell_mode_feedback_interface,
};

static const struct wl_message _wl_fullscreen_shell_requests[] = {
	{ "release", "", types + 0 },
	{ "present_surface", "?ou?o", types + 1 },
	{ "present_surface_for_mode", "ooin", types + 4 },
};

static const struct wl_message _wl_fullscreen_shell_events[] = {
	{ "capability", "u", types + 0 },
};

WL_EXPORT const struct wl_interface _wl_fullscreen_shell_interface = {
	"_wl_fullscreen_shell", 1,
	3, _wl_fullscreen_shell_requests,
	1, _wl_fullscreen_shell_events,
};

static const struct wl_message _wl_fullscreen_shell_mode_feedback_events[] = {
	{ "mode_successful", "", types + 0 },
	{ "mode_failed", "", types + 0 },
	{ "present_cancelled", "", types + 0 },
};

WL_EXPORT const struct wl_interface _wl_fullscreen_shell_mode_feedback_interface = {
	"_wl_fullscreen_shell_mode_feedback", 1,
	0, NULL,
	3, _wl_fullscreen_shell_mode_feedback_events,
};

